apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swellbeing-ui
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/chrisashwalker/swellbeing-gitops.git
    targetRevision: main
    path: charts/swellbeing-ui
    # helm:
      # valueFiles:
        # - values-production.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: swellbeing

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
