apiVersion: batch/v1
kind: Job
metadata:
  name: swellbeing-db-migrate
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
destination:
  server: https://kubernetes.default.svc
  namespace: swellbeing
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never

      containers:
        - name: migrate
          image: chrisashwalker/swellbeing-api:latest
          command:
            - flask
            - --app
            - swellbeing_api.app:app
            - db
            - upgrade
          env:
            - name: DATABASE_HOST
              value: "swellbeing-db-postgresql.swellbeing.svc.cluster.local"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: "swellbeing"
            - name: DATABASE_USER
              value: "swellbeing"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
